Repository joequincy/quantified-self-be, pull requests merged in 2019-07, with the labels that each got.

#15 Configure Travis CI
  .travis.yml
  config/jest.config.js
  package-lock.json
  package.json
  spec/index.spec.js
Labels: Housekeeping

#17 Meals Endpoints - Index
  README.md
  app.js
  migrations/20190702200035-create-meal.js
  migrations/20190702200442-create-meal-food.js
  models/meal.js
  models/mealfood.js
  package-lock.json
  package.json
  routes/api/v1/_api.js
  routes/api/v1/meals.js
  seeders/20190702232716-meal_seed.js
  seeders/20190702234140-food_seed.js
  seeders/20190703002406-mealfood_seed.js
  spec/api/v1/meals/index.spec.js
Labels: enhancement

#20 Filter Seeds By Environment
  .sequelizerc
  seeders/development/20190702232716-meal_seed.js
  seeders/development/20190702234140-food_seed.js
  seeders/development/20190703002406-mealfood_seed.js
  seeders/test/20190702190910-food_index_seed.js
  spec/api/v1/foods/index.spec.js
Labels: Housekeeping

#23 Add PR Template
  .github/PULL_REQUEST_TEMPLATE/default.md
Labels: Housekeeping

#28 Food Endpoints - Create: Update Endpoint
  README.md
  routes/api/v1/foods.js
  spec/api/v1/foods/update.spec.js
Labels: enhancement

#29 Create meal
  README.md
  routes/api/v1/meals.js
  spec/api/v1/meals/create.spec.js
Labels: enhancement

#31 Meal Endpoints: Delete
  README.md
  migrations/20190702200442-create-meal-food.js
  package.json
  routes/api/v1/meals.js
  spec/api/v1/meals/delete.spec.js
Labels: enhancement

#30 Food Endpoints - Create: Delete Endpoint
  README.md
  routes/api/v1/foods.js
  spec/api/v1/foods/delete.spec.js
Labels: enhancement

#32 Food/Meals Endpoints Documentation
  README.md
Labels: documentation

#33 Sprint 1 Complete
  .github/PULL_REQUEST_TEMPLATE.md
  .sequelizerc
  .travis.yml
  README.md
  app.js
  config/config.json
  config/jest.config.js
  config/jest.environment.js
  config/travis.jest.config.json
  migrations/20190702200035-create-meal.js
  migrations/20190702200442-create-meal-food.js
  models/food.js
  models/meal.js
  models/mealfood.js
  package-lock.json
  package.json
  routes/api/v1/_api.js
  routes/api/v1/foods.js
  routes/api/v1/meals.js
  seeders/development/20190702232716-meal_seed.js
  seeders/development/20190702234140-food_seed.js
  seeders/development/20190703002406-mealfood_seed.js
  seeders/test/20190702190910-food_index_seed.js
  spec/api/v1/foods/delete.spec.js
  spec/api/v1/foods/index.spec.js
  spec/api/v1/foods/new.spec.js
  spec/api/v1/foods/show.spec.js
  spec/api/v1/foods/update.spec.js
  spec/api/v1/meals/add_food.spec.js
  spec/api/v1/meals/create.spec.js
  spec/api/v1/meals/delete.spec.js
  spec/api/v1/meals/index.spec.js
  spec/api/v1/meals/remove_food.spec.js
  spec/api/v1/meals/show.spec.js
  spec/index.spec.js
Labels: Housekeeping

#34 Add CORS Support
  app.js
  helpers/index.js
  models/food.js
  models/meal.js
  package-lock.json
  package.json
  routes/api/v1/foods.js
  routes/api/v1/meals.js
Labels: enhancement
